# Generated by Django 4.0.3 on 2022-05-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facial', '0002_permitted_test_unknown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detected',
        ),
        migrations.DeleteModel(
            name='Permitted',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Unknown',
        ),
    ]
